# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial
services:
  - docker
language: generic
compiler: gcc
notifications:
  email:
    recipients:

env:
  global:
    - CXXFLAGS="-Wall -Wextra"
    - WARNINGS_OK=false
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO=noetic  TEST=clang-format,catkin_lint
    - ROS_DISTRO=noetic
    - ROS_DISTRO=melodic
    - ROS_DISTRO=kinetic  BEFORE_SCRIPT="\$CI_SOURCE_PATH/.travis.before_script"

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh
