# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  global:
    # script do be executed in docker container
    BEFORE_SCRIPT=./warehouse_ros_mongo/.travis.before_script
  matrix:
    - ROS_DISTRO=kinetic  ROS_REPO=ros              TEST=clang-format
    - ROS_DISTRO=kinetic  ROS_REPO=ros
    - ROS_DISTRO=melodic  ROS_REPO=ros

before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh
