# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial
services:
  - docker
language: generic
compiler: gcc
notifications:
  email:
    recipients:

env:
  global:
    - CXXFLAGS="-Wall -Wextra"
    - WARNINGS_OK=false
    - ROS_REPO=ros
    - UPSTREAM_WORKSPACE=rosinstall
  matrix:
    - ROS_DISTRO=melodic  TEST=clang-format,catkin_lint
    - ROS_DISTRO=melodic  BEFORE_SCRIPT="apt-get -qq install -y mongodb-server && service mongodb start"

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh
