# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Format

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install clang-format-10
      run: sudo apt-get install clang-format-10
    - uses: pre-commit/action@v2.0.0
    - name: Comment on PR if checks fail
      if: failure()
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'The format checks failed :(, Here are instructions for running pre-commit to fix the formatting: https://github.com/ros-planning/moveit2/wiki/pre-commit.'
          })
